name: Terraform Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  # push:
  #   branches: 
  #     - dev
    # paths:
    #   - terraform/**

jobs:
  Terraform-Checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform validate init
      id: init
      run: terraform init -backend=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
    
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

      # - name: Pause 15min to verify bucket creation
      #   run: sleep 900

      # - name: Terraform destroy
      #   run: terraform destroy -auto-approve

  Summary:
    needs: [Terraform-Checks]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          INFO1=${{ needs.Terraform-Checks.outputs.status }}

          echo '##  Preparing Build Summary ' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform-Checks  | $INFO1 |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY